### PR TITLE
Procedure page

### PR DESCRIPTION
**Pull request by wakig**
There are still some issues that I'm trying to fix, such as the card for the procedure step, in which I'm trying to include the number in the box. I will also improve the spacing and sizing soon.

For the venues, I used flexbox for now because I don't know how to use Bootstrap yet. It also messes up when I reduce the screen size hehe

### CODE REVIEW

**Comment by daniddelrio** [comment]
For the number in the box, you can style the number [like so](https://css-tricks.com/custom-list-number-styling/). This entails removing the initial number using `list-style-type: none` (like what you put) and instead styling the number using the `::before` pseudoselector.

As for the venue cards, I suggest using [Grid CSS](https://css-tricks.com/snippets/css/complete-guide-grid/), and using the [auto-fit](https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/) property of Grid to make the grid responsive (i.e. the number of columns adjusts when you resize the window). Don't make the card-container have a fixed width and height so that it adjusts when you resize, but do make the card itself have a fixed width and height (using `px` as the unit). The goal is that the width and height of the container adjusts when you resize but the card stays the same size.

Lastly, yes please improve the spacing! Specifically in between each section

**Review by daniddelrio — CHANGES_REQUESTED** [review]
Check my comment above :)

**Comment by wakig** [comment]
^Does this look better? Thanks!

**Review by daniddelrio — APPROVED** [review]
Looks great, thanks Waki!

**Pull request merged**
